import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./theme-registry";
import { cookies } from "next/headers";
import { VaultSessionProvider } from "@/context/vault-session";
import { UserProvider } from "@/context/user-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const initialMode =
    (cookieStore.get("theme-mode")?.value as "light" | "dark") || "light";
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <VaultSessionProvider>
          <UserProvider>
            <ThemeRegistry initialMode={initialMode}>{children}</ThemeRegistry>
          </UserProvider>
        </VaultSessionProvider>
      </body>
    </html>
  );
}
