"""create vault and vault  items

Revision ID: 28c1377b6285
Revises: 32e93ba17b43
Create Date: 2026-09-01 17:39:51.858892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28c1377b6285"
down_revision: Union[str, Sequence[str], None] = "32e93ba17b43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vaults",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_vault_key", sa.Text(), nullable=False),
        sa.Column("vault_key_iv", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "vault_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("LOGIN", "CARD", "NOTE", "IDENTITY", "SSH_KEY", name="vault_item_type"),
            nullable=False,
        ),
        sa.Column("encrypted_title", sa.Text(), nullable=False),
        sa.Column("title_iv", sa.String(length=64), nullable=False),
        sa.Column("encrypted_data", sa.Text(), nullable=False),
        sa.Column("data_iv", sa.String(length=64), nullable=False),
        sa.Column("favorite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("delete_status", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vault_items_vault_id"), "vault_items", ["vault_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_vault_items_vault_id"), table_name="vault_items")
    op.drop_table("vault_items")
    op.drop_table("vaults")
    sa.Enum(name="vault_item_type").drop(op.get_bind(), checkfirst=True)
