"""add delete_status to users

Revision ID: 32e93ba17b43
Revises: 7a68fac34314
Create Date: 2026-08-24 15:58:23.588290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e93ba17b43'
down_revision: Union[str, Sequence[str], None] = '7a68fac34314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_status', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_status')
    # ### end Alembic commands ###
