"""add 2fa and hint

Revision ID: b7f05e46a393
Revises: cc056257cc90
Create Date: 2026-09-06 15:24:59.316397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f05e46a393'
down_revision: Union[str, Sequence[str], None] = 'cc056257cc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('master_password_hint', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'master_password_hint')
    # ### end Alembic commands ###
