"""deleted at and verification status for users

Revision ID: cc056257cc90
Revises: 28c1377b6285
Create Date: 2026-09-05 09:12:53.731859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc056257cc90'
down_revision: Union[str, Sequence[str], None] = '28c1377b6285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
